[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.157.0",
]

[dependency-groups]
dev = [
    "streamlit>=1.48.1",
]
